name: Build Moto G Stylus NetHunter Kernel

on:
  workflow_dispatch: # This adds a manual "Play" button so you can trigger it from your phone

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build NetHunter Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com
          kernel-branch: lineage-21.0
          config: milanf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          anykernel3: true
          nethunter: true
          nethunter-patch: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
