name: Build Moto G Stylus Latest NetHunter Kernel

on:
  workflow_dispatch: # Allows manual trigger from your device

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build NetHunter Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_motorola_sm6375
          kernel-branch: lineage-23.2
          config: milanf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 16
          anykernel3: true
          nethunter: true
          nethunter-patch: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
