name: Build Moto G Stylus Latest NetHunter Kernel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build NetHunter Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_motorola_sm6375
          ref: lineage-23.2
          path: kernel-source

      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./kernel-source/
          config: gki_defconfig
          merge-configs: '["arch/arm64/configs/vendor/ext_config/lineage_moto-holi.config"]'
          arch: arm64
          anykernel3: true
          nethunter: true
          nethunter-patch: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
